### PR TITLE
provision agent yml fix

### PR DESCRIPTION
**Pull request by gallernd**
I could not run the install/provision agent task. After looking at the code, I found a small issue.  

Please take a look at this PR, as I hope it will be acceptable to you.

### CODE REVIEW

**Comment by sparkacus** [comment]
Wish I had looked here before spending my time debugging and working on a fix to find someone had already done it :)

**Comment by eexit** [comment]
I confirm this fix works. Please merge when you get a chance.
Thanks :)

**Comment by muram** [comment]
Added user story to test/review and merge.
TAT:  < 1 week

**Comment by muram** [comment]
All checks passed (working on re-activating travis-ci for future PRs checks)

```bash
PLAY RECAP ***********************************************************************************************************
i-023b5bf3f9da04df6        : ok=13   changed=5    unreachable=0    failed=0    skipped=24   rescued=0    ignored=0
i-0364d8ba4b6429114        : ok=15   changed=7    unreachable=0    failed=0    skipped=23   rescued=0    ignored=0
i-082f300e4a7d6e2d3        : ok=15   changed=7    unreachable=0    failed=0    skipped=23   rescued=0    ignored=0
```

```bash
===== LOADING ROLE ===== 
Checking role metadata tags 
Checking role platforms 
Checking role cloud platforms 
Checking role dependencies 
 
===== LINTING ROLE ===== 
yamllint OK. 
ansible-lint OK. 
 
===== IMPORTING ROLE: al_agents ===== 
 
Updating repository versions... 
Import completed with 0 warnings and 0 errors 
```

**Comment by muram** [comment]
Thanks @gallernd this looks good.

**Pull request merged**
